export const ROUTE_HOMEPAGE = '/'
export const ROUTE_WELCOMEPAGE = '/welcome'
export const ROUTE_RULES = '/rules'
export const ROUTE_PROJECT = '/dragons-of-mugloar'
export const ROUTE_DASHBOARD = '/dashboard'
