export const ROUTE_WELCOMEPAGE = '/dragons-of-mugloar/welcome'
export const ROUTE_RULES = '/dragons-of-mugloar/rules'
export const ROUTE_HOMEPAGE = '/dragons-of-mugloar'
export const ROUTE_INIT = '/'
export const ROUTE_DASHBOARD = '/dragons-of-mugloar/dashboard'
